# Generated by Django 4.0.5 on 2023-03-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendientes',
            options={'ordering': ['-created'], 'verbose_name': 'Pendientes', 'verbose_name_plural': 'Pendientes'},
        ),
        migrations.AlterField(
            model_name='pendientes',
            name='Area',
            field=models.CharField(choices=[('SubAcademica', 'SubAcademica'), ('SubAdministrativa', 'SubAdministrativa'), ('SubPlaneacion', 'SubPlaneacion')], max_length=30, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='pendientes',
            name='estado',
            field=models.CharField(choices=[('En Proceso', 'En Proceso'), ('Pendiente', 'Pendiente'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=25, verbose_name='Estado'),
        ),
    ]
