# Generated by Django 4.0.5 on 2023-03-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendientes', '0004_alter_pendientes_area_alter_pendientes_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendientes',
            name='Area',
            field=models.CharField(choices=[('SubPlaneacion', 'SubPlaneacion'), ('SubAdministrativa', 'SubAdministrativa'), ('SubAcademica', 'SubAcademica')], max_length=30, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='pendientes',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Finalizada', 'Finalizada'), ('En Proceso', 'En Proceso')], default='Pendiente', max_length=25, verbose_name='Estado'),
        ),
    ]
