# Generated by Django 4.0.5 on 2023-03-10 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pendientes', '0007_alter_pendientes_area_alter_pendientes_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendientes',
            name='Area',
            field=models.CharField(choices=[('SubAcademica', 'SubAcademica'), ('SubAdministrativa', 'SubAdministrativa'), ('SubPlaneacion', 'SubPlaneacion')], max_length=30, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='pendientes',
            name='estado',
            field=models.CharField(choices=[('Finalizada', 'Finalizada'), ('En Proceso', 'En Proceso'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=25, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
