# Generated by Django 4.1.5 on 2023-03-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendientes', '0010_alter_pendientes_area_alter_pendientes_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendientes',
            name='porcentaje',
            field=models.CharField(choices=[('50%', '50%'), ('0%', '0%'), ('25%', '25%'), ('75%', '75%')], default='0%', max_length=10, verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='pendientes',
            name='Area',
            field=models.CharField(choices=[('SubPlaneacion', 'SubPlaneacion'), ('SubAdministrativa', 'SubAdministrativa'), ('SubAcademica', 'SubAcademica')], max_length=30, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='pendientes',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Finalizada', 'Finalizada'), ('En Proceso', 'En Proceso')], default='Pendiente', max_length=25, verbose_name='Estado'),
        ),
    ]
